### ISSUE TITLE
0.1 Milestone

### ISSUE THREAD

**Issue by jc4p** [jc4p/lol-mechanics-tracker#1]
# Version 0.1

Goal: Functioning prototypes of all vital components. If there's anything I'm planning to do which might not work as planned, or any hidden obstacles I haven't thought of yet, now's the time to go exploring.

- [x] live CS tracking, without noticeable GPU/CPU hit
- [ ] Riot API integration to record champ, lane, etc
- [ ] Save to CSV
- [ ] Investigate if a centralized database would be necessary/helpful

**Comment by jc4p** [comment]
What about ward tracking? If better picture-in-picture detection comes as part of future plans for #2 pre 0.1 release, ward tracking (and where you/they are placing the wards) would be an easy add i think.

**Comment by jc4p** [comment]
I think the earlier-on we add a error reporting service the better it'll be, too. There's [some code](https://github.com/jc4p/lol-mechanics-tracker/blob/cea29a056c96825d029f6add64a589b9b8fc7f10/LolTracker/MainForm.cs#L113) already to save frames OCR couldn't process, adding this logic to a helper class would mean it'd be done more as the code base evolves. Hell, it'd be usable for generating the look-up archives ^ talks about too.

**Comment by ian-campbell** [comment]
What are the dependencies for this program?

**Comment by jc4p** [comment]
@ian-campbell it's a bit up in the air (this is both the product I was trying to build and the library I built to use for it combined in one codebase rn). it only runs in side of Visual Studio, and I believe you need to also install the [Windows SDK](https://developer.microsoft.com/en-us/windows/downloads/windows-10-sdk)
